blank_issues_enabled: true
contact_links:
  - name: 问题讨论 & Ask a Question, Help, Discuss
    url: https://github.com/Patchouli-CN/hexo-theme-patchouli/discussions
    about: I have a question, help for hexo-theme-patchouli (e.g. Customize)
